theme: jekyll-theme-leap-day
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - Análisis_Malware.md
  - Desarrollo_Seguro.md
  - Ethical_Hacking.md
  - Lista_de_Pruebas.md
  - Hacking_Buscadores.md
  - Hacking_web.md
  - Metasploit.md
  - OSINT.md
  - Snort.md
  - Triage_Informático.md
  - README.md
  - Imagenes
